import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/globals.css";
import React from "react"; // Add import for React
import dynamic from "next/dynamic";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Loads DBConnector dynamically on SSR
const DBConnector = dynamic(() => import("@/components/mongodb/DBConnector"), {
  loading: () => <p>Loading...</p>,
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {
          // If in build phase then don't call DBConnector
          process.env.NEXT_PHASE !== "phase-production-build" && <DBConnector />
        }
      </body>
    </html>
  );
}
