import React, { useState } from "react";
import ConfigEditorModal from "./UI/ConfigEditorModal";
import MyButton from "./UI/button/MyButton";
import { PostFormProps } from "@/types";
import { tinkerforgeDTO } from "@/models/zTinkerforgeSensor.schema";
import { v4 as uuidv4 } from "uuid";

// Predefined sensor types with their required configuration fields (just as a plug for testing functionality).
const sensorTypes = [
  {
    name: "GPIB",
    configFields: [
      { key: "frequence", required: true },
      { key: "voltage", required: false },
      { key: "temperature", required: false },
    ],
  },
  {
    name: "Tinkerforge",
    configFields: [
      { key: "interval", required: true },
      { key: "trigger only on change", required: true },
      { key: "description", required: true },
      { key: "topic", required: true },
      { key: "unit", required: true },
    ],
  },
];

/**
 * A form component for creating and adding new configurations for posts.
 *
 * This component provides:
 * - Sensor type selection: Allows the user to choose between different sensor types (GPIB, Tinkerforge).
 * - Dynamic configuration fields: Based on the selected sensor type, the form updates the required configuration fields.
 * - Editing mode: If a post is passed via `postToEdit`, the form pre-fills with existing values.
 * - Creation mode: If no `postToEdit` is provided, a new post is created with default fields.
 * - Form submission handling: On submission, the post is either edited or created, and the input fields are cleared afterward.
 * 
 * @component
 * @param {PostFormProps} props - Props for the PostForm component.
 * @param {(post: { title: string, description: string, id: number }) => void}
 * props.create - Callback function to handle creating a new post.
 *
 * @returns {JSX.Element} A form with controlled input fields for post creation.
 * 
 * @example
 * // Example usage of PostForm component
 * const [postToEdit, setPostToEdit] = useState<Post | null>(null);
 * const createPost = (newPost: Post) => {
     setPosts([...posts, newPost]);
     setModal(false);
   };
   const editPost = (updatedPost: Post) => {
       setPosts(posts.map((p) => (p.id === updatedPost.id ? updatedPost : p)));
       setModal(false);
       setPostToEdit(null);
    };
 * 
 * <PostForm create={createPost} edit={editPost} postToEdit={postToEdit} />
 * 
 */
const PostForm: React.FC<PostFormProps> = ({ create, edit, postToEdit }) => {
  // Helper function to generate the current date
  const getCurrentDateISOString = (): string => {
    return new Date().toISOString();
  };

  // Default post structure used when creating a new sensor post, to fill the input fields with empty/default values
  const defaultPost: tinkerforgeDTO = {
    id: "",
    uid: 0,
    description: "",
    date_created: getCurrentDateISOString(),
    date_modified: getCurrentDateISOString(),
    enabled: false,
    label: "",
    config: {},
    on_connect: [],
  };

  // State for managing the input values of the form
  const [post, setPost] = useState<tinkerforgeDTO>(postToEdit || defaultPost);

  // State for managing the current type of sensor to be created
  const [selectedSensorType, setSelectedSensorType] = useState<string>("");

  const handleSensorTypeChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const selectedType = e.target.value;
    setSelectedSensorType(selectedType);

    // find configuration for selected sensorType
    const selectedConfig =
      sensorTypes.find((type) => type.name === selectedType)?.configFields ||
      [];

    // set fields of configuration
    const newConfig = selectedConfig.reduce(
      (configEntities, field) => {
        configEntities[field.key] = "";
        return configEntities;
      },
      {} as Record<string, string>,
    );

    setPost((prev) => ({
      ...prev,
      config: Object.fromEntries(
        Object.entries(newConfig).map(([key, value]) => [
          key,
          {
            description: value,
            interval: 0,
            trigger_only_on_change: false,
            topic: "",
            unit: "",
          },
        ]),
      ),
      id: selectedType === "Tinkerforge" ? "AutoGeneratedHost" : "",
      port: selectedType === "Tinkerforge" ? 42 : 0,
    }));
  };

  React.useEffect(() => {
    // Update the form state whenever `postToEdit` changes
    if (postToEdit) {
      setPost(postToEdit); // editing mode
    } else {
      setPost(defaultPost); // creation mode => we clear all inputFields
    }
  }, [postToEdit]); // Runs whenever `postToEdit` changes

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault(); // So that the page does not refresh after pressing the button

    // We change the state indirectly. We create a new array where we write our old one. And at the end comes the new element

    if (postToEdit) {
      edit({ ...post, date_modified: getCurrentDateISOString() });
    } else {
      create({ ...post, id: uuidv4() }); // Generate a unique ID based on the current timestamp
    }

    setPost({
      id: "",
      uid: 0,
      description: "",
      date_created: getCurrentDateISOString(),
      date_modified: getCurrentDateISOString(),
      enabled: false,
      label: "",
      config: {},
      on_connect: [],
    }); // After inserting Element, we empty InputFields
  };

  return (
    <form>
      <label
        htmlFor="sensorType"
        style={{
          display: "block",
          marginBottom: "4px",
        }}
      >
        Sensor Type
      </label>
      <select
        id="sensorType"
        value={selectedSensorType}
        onChange={handleSensorTypeChange}
        style={{
          width: "100%",
          padding: "5px",
          border: "1px solid teal",
          marginBottom: "16px",
        }}
      >
        <option value="">Select Sensor Type</option>
        {sensorTypes.map((type) => (
          <option key={type.name} value={type.name}>
            {type.name}
          </option>
        ))}
      </select>

      {/* For editing the configuration */}
      <ConfigEditorModal
        config={post.config || {}} // Provide an empty object if `config` is not defined
        setConfig={(newConfig) =>
          setPost((prev) => ({
            ...prev,
            config: newConfig as Record<
              string,
              {
                description: string | null;
                interval: number;
                trigger_only_on_change: boolean;
                topic: string;
                unit: string;
              }
            >,
          }))
        }
        selectedSensorType={selectedSensorType}
      />

      <MyButton onClick={handleSubmit}>
        {postToEdit ? "Save changes" : "Add new sensor"}
      </MyButton>
    </form>
  );
};

export default PostForm;
