#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

 npx prettier --write . "tests/data/*.json"  

 if ! npx prettier --check . "tests/data/*.json"; then
   echo "Formatting errors found. Please fix them before committing."
   exit 1
 fi

  npm run lint
 
 #Dont remove this, the tests are not done 
# npm test

